### ISSUE TITLE
Build issue on idf 4.4

### ISSUE THREAD

**Issue by gt-inno** [nopnop2002/esp-idf-can2http#3]
Enviroment windows 10
ESP32 IDF version 4.4

On idf.py build the following error occurs

C:/Users/gt-in/VScode-projects/esp-idf-can2http-main/main/http_post.c: In function '_http_event_handler':
C:/Users/gt-in/VScode-projects/esp-idf-can2http-main/main/http_post.c:95:8: error: 'HTTP_EVENT_REDIRECT' undeclared (first use in this function); did you mean 'HTTP_EVENT_HEADER_SENT'?
   case HTTP_EVENT_REDIRECT:
        ^~~~~~~~~~~~~~~~~~~
        HTTP_EVENT_HEADER_SENT

**Comment by nopnop2002** [comment]
Thanks for the report.
Fixed in the latest version.

**Comment by gt-inno** [comment]
New versions does not include the application configuration to set the specific parameters.Is it under a different option ?

**Comment by nopnop2002** [comment]
I don't know what kind of problem it will cause.

**Comment by gt-inno** [comment]
Never mind, the menu-config i was using was in a different folder.

**Comment by gt-inno** [comment]
more errors came up now and building stopped once again after configuration.

In file included from C:/Users/gt-in/VScode-projects/esp-idf-can2http/main/http_post.c:16:
C:/Users/gt-in/VScode-projects/esp-idf-can2http/main/http_post.c: In function 'http_rest_with_url':
C:/Espressif/frameworks/esp-idf-v4.4.3/components/log/include/esp_log.h:276:27: error: format '%lld' expects argument of type 'long long int', but argument 7 has type 'int' [-Werror=format=]
 #define LOG_COLOR(COLOR)  "\033[0;" COLOR "m"

**Comment by nopnop2002** [comment]
Fixed.
Please try with the latest version.

**Comment by gt-inno** [comment]
Perfect. Build is now successful.
