### ISSUE TITLE
Failed on vscode idf 4.4 and 5.0

### ISSUE THREAD

**Issue by jokokiswan** [nopnop2002/esp-idf-can2http#4]
How to replicate your success sample?
My env:
Vscode 1.70
Esp idf 4.4.4 and 5.0
Devkit v1 esp32

Both TWAI and mdns failed.

**Comment by nopnop2002** [comment]
Too little information to answer.
I'd like at least a build-time log and a run-time log.

**Comment by jokokiswan** [comment]
Already did, but i got no receive or send on CAN bus.

**Comment by nopnop2002** [comment]
To answer, I need at least a build-time log and a run-time log.

have you seen closed issues?
There are many solutions in closed issues.

**Comment by jokokiswan** [comment]
run time:
←]633;P;IsWindows=True
←]633;A←]633;P;Cwd=E:\project_esp\esp-idf-can2http-mainPS E:\project_esp\esp-idf-can2http-main> ←]633;Bset IDF_PATH=C:\Users\pro-maker\esp\esp-idf
←]633;C
←]633;E;set IDF_PATH=C:\Users\pro-maker\esp\esp-idf←]633;D;0←]633;A←]633;P;Cwd=E:\project_esp\esp-idf-can2http-mainPS E:\project_esp\esp-idf-can2http-main> ←]633;BC:\Users\pro-maker\.espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe C:\Users\pro-maker\esp\esp-idf\tools\idf_monitor.py -p COM7 -b 115200 --toolchain-prefix xtensa-esp32-elf- --target esp32 e:\project_esp\esp-idf-can2http-main\build\can2http.elf
←]633;C←[0;33m--- WARNING: GDB cannot open serial ports accessed as COMx←[0m
←[0;33m--- Using \\.\COM7 instead...←[0m
←[0;33m--- idf_monitor on \\.\COM7 115200 ---←[0m
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6952
load:0x40078000,len:15500
ho 0 tail 12 room 4
load:0x40080400,len:3844
0x40080400: _init at ??:?

entry 0x4008064c
I (29) boot: ESP-IDF v5.0.1-3-g886e98a2c1 2nd stage bootloader
I (29) boot: compile time 21:18:50
I (29) boot: chip revision: v3.0
I (33) boot.esp32: SPI Speed      : 40MHz
I (38) boot.esp32: SPI Mode       : DIO
I (43) boot.esp32: SPI Flash Size : 2MB
I (47) boot: Enabling RNG early entropy source...
I (53) boot: Partition Table:
I (56) boot: ## Label            Usage          Type ST Offset   Length
I (63) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (71) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (78) boot:  2 factory          factory app      00 00 00010000 00100000
I (86) boot:  3 storage          Unknown data     01 82 00110000 000f0000
I (93) boot: End of partition table
I (97) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=2704ch (159820) map
I (164) esp_image: segment 1: paddr=00037074 vaddr=3ffb0000 size=03444h ( 13380) load
I (169) esp_image: segment 2: paddr=0003a4c0 vaddr=40080000 size=05b58h ( 23384) load
I (179) esp_image: segment 3: paddr=00040020 vaddr=400d0020 size=ac51ch (705820) map
I (434) esp_image: segment 4: paddr=000ec544 vaddr=40085b58 size=0fe88h ( 65160) load
I (472) boot: Loaded app from partition at offset 0x10000
I (472) boot: Disabling RNG early entropy source...
I (484) cpu_start: Pro cpu up.
I (484) cpu_start: Starting app cpu, entry point is 0x4008130c
0x4008130c: call_start_cpu1 at C:/Users/pro-maker/esp/esp-idf/components/esp_system/port/cpu_start.c:142

I (0) cpu_start: App cpu up.
I (500) cpu_start: Pro cpu start user code
I (500) cpu_start: cpu freq: 160000000 Hz
I (500) cpu_start: Application information:
I (505) cpu_start: Project name:     can2http
I (510) cpu_start: App version:      1
I (515) cpu_start: Compile time:     Feb 28 2023 07:59:27
I (521) cpu_start: ELF file SHA256:  67476d8b3cef2a37...
I (527) cpu_start: ESP-IDF:          v5.0.1-3-g886e98a2c1
I (533) cpu_start: Min chip rev:     v0.0
I (537) cpu_start: Max chip rev:     v3.99 
I (542) cpu_start: Chip rev:         v3.0
I (547) heap_init: Initializing. RAM available for dynamic allocation:
I (554) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (560) heap_init: At 3FFB7E38 len 000281C8 (160 KiB): DRAM
I (566) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (573) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (579) heap_init: At 400959E0 len 0000A620 (41 KiB): IRAM
I (587) spi_flash: detected chip: generic
I (590) spi_flash: flash io: dio
W (594) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (608) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (662) MAIN: ESP_WIFI_MODE_STA
I (672) MAIN: ESP-IDF Ver5.0
I (672) MAIN: ESP_IDF_VERSION 327681
I (682) wifi:wifi driver task: 3ffbfeb8, prio:23, stack:6656, core=0
I (682) system_api: Base MAC address is not set
I (682) system_api: read default base MAC address from EFUSE
I (702) wifi:wifi firmware version: 17afb16
I (702) wifi:wifi certification version: v7.0
I (702) wifi:config NVS flash: enabled
I (702) wifi:config nano formating: disabled
I (702) wifi:Init data frame dynamic rx buffer num: 32
I (712) wifi:Init management frame dynamic rx buffer num: 32
I (712) wifi:Init management short buffer num: 32
I (722) wifi:Init dynamic tx buffer num: 32
I (722) wifi:Init static rx buffer size: 1600
I (732) wifi:Init static rx buffer num: 10
I (732) wifi:Init dynamic rx buffer num: 32
I (732) wifi_init: rx ba win: 6
I (742) wifi_init: tcpip mbox: 32
I (742) wifi_init: udp mbox: 6
I (742) wifi_init: tcp mbox: 6
I (752) wifi_init: tcp tx win: 5744
I (752) wifi_init: tcp rx win: 5744
I (762) wifi_init: tcp mss: 1440
I (762) wifi_init: WiFi IRAM OP enabled
I (762) wifi_init: WiFi RX IRAM OP enabled
I (792) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (902) wifi:mode : sta (e0:5a:1b:5f:e6:f8)
I (902) wifi:enable tsf
I (912) MAIN: wifi_init_sta finished.
I (962) wifi:new:<7,0>, old:<1,0>, ap:<255,255>, sta:<7,0>, prof:1
I (1782) wifi:state: init -> auth (b0)
I (1792) wifi:state: auth -> assoc (0)
I (1802) wifi:state: assoc -> run (10)
I (1812) wifi:connected with Wedus, aid = 88, channel 7, BW20, bssid = d4:4f:67:3a:7d:f0
I (1812) wifi:security: WPA2-PSK, phy: bgn, rssi: -75
I (1842) wifi:pm start, type: 1

I (1872) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (4842) esp_netif_handlers: sta ip: 192.168.10.50, mask: 255.255.255.0, gw: 192.168.10.1
I (4842) MAIN: got ip:192.168.10.50
I (4842) MAIN: connected to ap SSID:Wedus password:270247673
I (4852) MAIN: mdns hostname set to: [esp32-server]
I (4852) MAIN: Bitrate is 125 Kbit/s
I (4862) MAIN: CTX_GPIO=21
I (4862) MAIN: CRX_GPIO=22
I (4862) MAIN: Driver installed
I (4872) MAIN: Driver started
I (4872) MAIN: Initializing SPIFFS file system
I (4992) MAIN: Partition size: total: 896321, used: 753
I (4992) MAIN: d_name=can2http.csv d_ino=0 d_type=1
I (5042) MAIN: Mount SPIFFS filesystem
I (5042) MAIN: build_table file=/spiffs/can2http.csv
I (5042) MAIN: build_table _ntopic=4
I (5042) main: topics=[0] frame=0 canid=0x101 topic=[/post] topic_len=5
I (5052) main: topics=[1] frame=1 canid=0x101 topic=[/post] topic_len=5
I (5062) main: topics=[2] frame=0 canid=0x103 topic=[/post] topic_len=5
I (5062) main: topics=[3] frame=1 canid=0x103 topic=[/post] topic_len=5
I (5072) SERVER: Start task_parameter=192.168.10.50
I (5072) HTTP: Start HTTP Client: connect to http://httpserver.local:8000
I (5072) TWAI: task start
I (5092) twai_rx: topics=[0] frame=0 canid=0x101 topic=[/post] topic_len=5
I (5082) SERVER: Starting server on http://192.168.10.50:8000
I (5102) twai_rx: topics=[1] frame=1 canid=0x101 topic=[/post] topic_len=5
I (5112) twai_rx: topics=[2] frame=0 canid=0x103 topic=[/post] topic_len=5
I (5122) twai_rx: topics=[3] frame=1 canid=0x103 topic=[/post] topic_len=5
I (63122) wifi:<ba-add>idx:0 (ifx:0, d4:4f:67:3a:7d:f0), tid:0, ssn:7, winSize:64

HTTP ALREADY OK,

do i need this solution? R2:150 ohms(Not working at 120 ohms)

**Comment by nopnop2002** [comment]
Your setup is to receive only these CAN messages.
```
I (5042) main: topics=[0] frame=0 canid=0x101 topic=[/post] topic_len=5
I (5052) main: topics=[1] frame=1 canid=0x101 topic=[/post] topic_len=5
I (5062) main: topics=[2] frame=0 canid=0x103 topic=[/post] topic_len=5
I (5062) main: topics=[3] frame=1 canid=0x103 topic=[/post] topic_len=5
```

**Comment by jokokiswan** [comment]
how to enable receive all? thank you

**Comment by nopnop2002** [comment]
>how to enable receive all? thank you

Read README.md

**Comment by nopnop2002** [comment]
You can use this to check if the termination resistor values are correct.

https://github.com/nopnop2002/esp-idf-candump

**Comment by jokokiswan** [comment]
Thank you, mcp2515 are much easier than vp230, but you could :)

**Comment by nopnop2002** [comment]
Since MCP2515 is a Can Controller, it cannot be used instead of VP230.
VP230 is Can Tranceiver.


The ATMega328 has neither a Can controller nor a Can transceiver, so both are required.
The ESP32 has a Can controller in-chip, so only a Can transceiver is required.
We often see ESP32+MCP2515+MCP2551, but this is a silly attempt.

**Comment by jokokiswan** [comment]
I think you shoud describe to us what kind esp32 you used, i used wroom 32s ( dev kit v1 :), very old ), TWAI response nothing. I tried on arduino with same board same can transceiver, it has rx tx responses, i did 150 ohm termination.

**Comment by nopnop2002** [comment]
I have many (Over 40) ESP32's.
It is not possible to examine all SoCs.

In ESP32 whose chip version is Rev2 or higher, the role of register bits related to CAN communication has been changed to mean "halve the communication speed".   
Therefore, newer cores with chip version 2 or higher may not be able to communicate properly.
See [here](https://github.com/sandeepmistry/arduino-CAN/issues/62) for detail.

**Comment by jokokiswan** [comment]
This one is very good infos, thank you

**Comment by nopnop2002** [comment]
You can see your chip revision with the code below.

```
#include "esp_chip_info.h"


    // Print chip information
    esp_chip_info_t chip_info;
    esp_chip_info(&chip_info);
    printf("chip_info.model is %d\n", chip_info.model);
    printf("chip_info.revision is %d\n", chip_info.revision);
    printf("chip_info.cores is %d\n", chip_info.cores);
```

**Comment by nopnop2002** [comment]
This article is easier to understand.
https://www.esp32.com/viewtopic.php?t=15581

This fuature is enabled when CONFIG_ESP32_REV_MIN >= 2.   


You are probably enabled.
>I (29) boot: chip revision: v3.0
